# Generated by Django 2.2.14 on 2021-09-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210923_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
